name: Python CI

on: [push, pull_request]

jobs:
  format-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-html
        
    - name: Check imports sorting with isort
      run: |
        isort --check-only .
        
    - name: Check formatting with Black
      run: |
        black --check .
        
    - name: Run tests with pytest
      run: |
        pytest -v --html=test_report.html --self-contained-html

    - name: Upload HTML report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: pytest-html-report
        path: test_report.html
